
MACRO(USE)
	FOREACH(arg ${ARGN})
		STRING(TOUPPER ${arg} ARG_U)
		FIND_PACKAGE(${arg})
		INCLUDE_DIRECTORIES(${ARG_U}_INCLUDE_DIRS)
	ENDFOREACH()
ENDMACRO()

MACRO(LINK EXE_NAME)
	FOREACH(arg ${ARGN})
		STRING(TOUPPER ${arg} ARG_U)
		TARGET_LINK_LIBRARIES(${EXE_NAME} ${ARG_U}_LIBRARIES)
	ENDFOREACH()
ENDMACRO()

# Usage: list_subdirectories(the_list_is_returned_here C:/cwd 1)
macro(list_subdirectories retval curdir return_relative)
	file(GLOB_RECURSE sub-dir RELATIVE ${curdir} * )
	set(list_of_dirs "")
	foreach(dir ${sub-dir})
		STRING(REGEX REPLACE "/[^/]+$" "" dir ${dir})
		if(IS_DIRECTORY ${curdir}/${dir})
			if (${return_relative})
				set(list_of_dirs ${list_of_dirs} ${dir})
			else()
				set(list_of_dirs ${list_of_dirs} ${curdir}/${dir})
			endif()
		endif()
	endforeach()
	set(${retval} ${list_of_dirs})
endmacro()


### Set the folders in Visual
MACRO(GROUP_FILES)
	list_subdirectories(SUB_DIRS ${CMAKE_CURRENT_SOURCE_DIR} 1)
	FOREACH(DIR ${SUB_DIRS})
		FILE(GLOB FILES ${DIR}/*.cpp ${DIR}/*.h)
		SOURCE_GROUP(${DIR} FILES ${FILES})
	ENDFOREACH()
ENDMACRO()
