#!/bin/bash

if [ -n "$1" ] && [ -e "$1" ] ; then
    DB_FILE_OPT="-f $1"
fi
PASSWORD=
filter=/tmp/filteraefddaef


echo '#!/usr/bin/env perl

use lib ($ENV{RLWRAP_FILTERDIR} or ".");
use RlwrapFilter;
use strict;

my $filter = new RlwrapFilter;
my $name = $filter -> name;
my @commands = ("ls", "cat", "add","addExisting", "copy", "rm", "mv", "file", "help", "exit", "quit", "passwd");
my @services =  @ARGV;

$filter -> completion_handler(\&complete);


$filter -> run;

sub complete {
  my($line, $prefix, @completions) =@_;

  my $nwords = scalar split /\s+/, $line;
  $nwords++ unless $prefix;   # TAB at start of a new (empty) argument
  if ($nwords <= 1) {
    return  grep(/^$prefix/, @commands);
  }

  if ($nwords == 2) {
    my $first = (split /\s+/, $line)[0];
    if ($first eq "copy"){
        return grep(/^$prefix/, @services);
    }
    if ($first eq "cat"){
        return grep(/^$prefix/, @services);
    }
    if ($first eq "rm"){
        return grep(/^$prefix/, @services);
    }
    if ($first eq "mv"){
        return grep(/^$prefix/, @services);
    }
    if ($first eq "file") {
        return grep(/^$prefix/, @completions);
    }
    return ();
  }

  return ();
}

' > $filter
chmod u+x $filter

help(){
    cat << EOF
Commands:

help
    This help.

cat {service}
    Get the password for this *serivice*.

ls 
    List all the existing services.

add {service} 
    Add a password for a service. If *password* is omitted then a new generated one is given.

addExisting {service}
    Add an already existing password for a service. The password will be asked durring the process.

copy {service}
    Copy to the clipbord the password for *service*. (Use xsel)

rm {service}
    Remove an existing service.

file {file}
    Change the db file.

passwd {file}
    Create a new db file with a new password.


EOF
}

doCrypteos(){
    echo $PASSWORD | crypteos-bin --hidden false $DB_FILE_OPT $@
}

updateServices(){
    services="$( (doCrypteos --list || askMasterPassword) | tr "\n" " " 2>/dev/null )" 
}

askMasterPassword(){
    stty -echo
    read -s -p "I need your password: " PASSWORD
    stty echo
    echo
    updateServices 
}

askNewPassword(){
    stty -echo
    read -s -p "I need your new password: " NEW_PASSWORD
    stty echo
    echo 
}

menu(){
    while [ "$reponse" != exit ] ; do 
        reponse="$(rlwrap -I -S 'crypteos> ' -pgreen -c -z "$filter $services" -o cat )"

        set -- $reponse 
        case "$1" in 
            help|h|\?)
                help
                ;;
            copy)
                if [ -n "$2" ] ; then
                    echo $PASSWORD | crypteos-bin --hidden false $DB_FILE_OPT --get "$2" | xsel
                else 
                    echo an argument is missing !
                fi
                ;;
            cat)
                if [ -n "$2" ] ; then
                    echo $PASSWORD | crypteos-bin --hidden false $DB_FILE_OPT --get "$2"
                else 
                    echo an argument is missing !
                fi
                ;;
            ls)
                echo $PASSWORD | crypteos-bin --hidden false $DB_FILE_OPT --list 
                ;;
            add)
                if [ -n "$2" ] ; then
                    echo $PASSWORD | crypteos-bin --hidden false $DB_FILE_OPT --add "$2"
                    updateServices
                else 
                    echo an argument is missing !
                fi
                ;;
            addExisting)
                if [ -n "$2" ] ; then
                    stty -echo
                    read -s -e -p "Enter the password to add: " new_password
                    echo 
                    stty echo
                    echo $PASSWORD | crypteos-bin --hidden false $DB_FILE_OPT --add "$2" --key "$new_password"
                    updateServices
                else 
                    echo an argument is missing !
                fi
                ;;
            rm)
                if [ -n "$2" ] ; then
                    echo $PASSWORD | crypteos-bin --hidden false $DB_FILE_OPT --remove "$2"
                    updateServices
                else 
                    echo an argument is missing !
                fi
                ;;
            mv)
                if [ -n "$2" ] ; then
                    echo $PASSWORD | crypteos-bin --hidden false $DB_FILE_OPT --rename "$2" --name "$3"
                    updateServices
                else 
                    echo an argument is missing !
                fi
                ;;    
            file)
                if [ -n "$2" ] ; then
                    DB_FILE_OPT="--file $2"
                    askMasterPassword
                else 
                    echo an argument is missing !
                fi
                ;;
            passwd)
                if [ -n "$2" ] ; then
                    askNewPassword
                    echo $PASSWORD | crypteos-bin --hidden false $DB_FILE_OPT --passwd "$2" --newpw "$NEW_PASSWORD"
                else 
                    echo an argument is missing !
                fi
                ;;
            exit|quit|q)
                exit 0
                ;;
            *)
                if [ -n "$reponse" ] ; then
                    echo "Command not found: '$reponse'"
                fi
                ;;
        esac
    done

}


askMasterPassword
menu
